/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface AaPlayerConverter {}
  interface AaPlayerConverterAttributes extends StencilHTMLAttributes {}

  interface AaPlayer {
    'mlt': string[];
  }
  interface AaPlayerAttributes extends StencilHTMLAttributes {
    'mlt'?: string[];
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AaPlayerConverter': Components.AaPlayerConverter;
    'AaPlayer': Components.AaPlayer;
    'AppRoot': Components.AppRoot;
  }

  interface StencilIntrinsicElements {
    'aa-player-converter': Components.AaPlayerConverterAttributes;
    'aa-player': Components.AaPlayerAttributes;
    'app-root': Components.AppRootAttributes;
  }


  interface HTMLAaPlayerConverterElement extends Components.AaPlayerConverter, HTMLStencilElement {}
  var HTMLAaPlayerConverterElement: {
    prototype: HTMLAaPlayerConverterElement;
    new (): HTMLAaPlayerConverterElement;
  };

  interface HTMLAaPlayerElement extends Components.AaPlayer, HTMLStencilElement {}
  var HTMLAaPlayerElement: {
    prototype: HTMLAaPlayerElement;
    new (): HTMLAaPlayerElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLElementTagNameMap {
    'aa-player-converter': HTMLAaPlayerConverterElement
    'aa-player': HTMLAaPlayerElement
    'app-root': HTMLAppRootElement
  }

  interface ElementTagNameMap {
    'aa-player-converter': HTMLAaPlayerConverterElement;
    'aa-player': HTMLAaPlayerElement;
    'app-root': HTMLAppRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
